export const SETTINGS_WORK_DAY_AVAIBLE = {
  SENIN: 'SENIN',
  SELASA: 'SELASA',
  RABU: 'RABU',
  KAMIS: 'KAMIS',
  JUMAT: 'JUMAT',
  SABTU: 'SABTU',
  MINGGU: 'MINGGU',
};

export const SETTINGS_KEY = {
  ADMIN_ID: 'ADMIN_ID',
  DEFAULT_DAY_TIME_START: 'DEFAULT_DAY_TIME_START',
  DEFAULT_DAY_TIME_END: 'DEFAULT_DAY_TIME_END',
  DEFAULT_WORK_DAY_AVAIBLE: 'DEFAULT_WORK_DAY_AVAIBLE',
  DEFAULT_BREAK_TIME_START: 'DEFAULT_BREAK_TIME_START',
  DEFAULT_BREAK_TIME_END: 'DEFAULT_BREAK_TIME_END',
  DEFAULT_TOTAL_MINUTE_WORK: 'DEFAULT_TOTAL_MINUTE_WORK',
};

export const SETTINGS_KEY_TYPE: Record<string, any> = {
  [SETTINGS_KEY.ADMIN_ID]: Array,
  [SETTINGS_KEY.DEFAULT_DAY_TIME_START]: String,
  [SETTINGS_KEY.DEFAULT_DAY_TIME_END]: String,
  [SETTINGS_KEY.DEFAULT_WORK_DAY_AVAIBLE]: Array,
  [SETTINGS_KEY.DEFAULT_BREAK_TIME_START]: String,
  [SETTINGS_KEY.DEFAULT_BREAK_TIME_END]: String,
  [SETTINGS_KEY.DEFAULT_TOTAL_MINUTE_WORK]: Number,
};

export const SETTINGS_KEY_DEFAULT_VALUE: Record<string, any> = {
  [SETTINGS_KEY.ADMIN_ID]: [process.env.SETTINGS_ADMIN_ID],
  [SETTINGS_KEY.DEFAULT_DAY_TIME_START]: '08:00',
  [SETTINGS_KEY.DEFAULT_DAY_TIME_END]: '17:00',
  [SETTINGS_KEY.DEFAULT_WORK_DAY_AVAIBLE]: Object.values(
    SETTINGS_WORK_DAY_AVAIBLE,
  ),
  [SETTINGS_KEY.DEFAULT_BREAK_TIME_START]: '12:00',
  [SETTINGS_KEY.DEFAULT_BREAK_TIME_END]: '13:00',
  [SETTINGS_KEY.DEFAULT_TOTAL_MINUTE_WORK]: 480,
};
