export const SKP_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITEED',
  APROVED: 'APROVED',
  REJECTED: 'REJECTED',
};

export const SKP_APPROACH = {
  KUALITATIF: 'KUALITATIF',
  KUANTITATIF: 'KUANTITATIF',
};

export const SKP_CASCADING = {
  NOT_YET: 'BELUM DI TENTUKAN',
  NON_DIRECT_CASCADING: 'NON DIRECT CASCADING',
  DIRECT_CASCADING: 'DIRECT CASCADING',
};

export const SKP_LAMPIRAN_DEFAULT = {
  SKEMA: 'SKEMA',
  SUMBER_DATA: 'SUMBER_DATA',
  KONSENKUENSI: 'KONSEKUENSI',
};
