services:

  api:
    env_file:
      - .env.prod
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - uploads_volume:/app/uploads

  postgres:
    env_file:
      - .env.prod
    restart: always

  redis:
    restart: always

volumes:
  uploads_volume:
    driver: local